### ISSUE TITLE
Reaction description for browsing

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#103]
In the web GUI for the database, each reaction should have a page that shows a table of populated schema fields (as well as the reaction image from #102). We need a tool to programmatically generate this table --- probably outputting HTML.

**Comment by connorcoley** [comment]
I went deep into RDKit's new svg drawing code for molecules and reactions. It's not going to be easy to get the flexibility we want using pure Python. Some of the useful information when rendering reactions (e.g., coordinates for the center of each molecule, offsets between them, locations of the "+" symbols, arrow) are not accessible outside of the C++ code.

**Comment by skearnes** [comment]
> I went deep into RDKit's new svg drawing code for molecules and reactions last night. For an MVP, we'll probably be content with rendering the reaction (reactants, agents, products) by itself and including annotations below in a tabular format.
> 
That sounds good to me.

> It's not going to be easy to get the flexibility we will eventually want using pure Python. Some of the useful information when rendering reactions (e.g., coordinates for the center of each molecule, offsets between them, locations of the "+" symbols, arrow) are not accessible outside of the C++ code.

Bummer. What about drawing each component separately and then putting them together manually with matplotlib?

**Comment by connorcoley** [comment]
> What about drawing each component separately and then putting them together manually with matplotlib?

That's how I wrote the original ASKCOS reaction drawing code. This could work well if we're using png renderings, but I'm not about the updated svg drawing code.
