### ISSUE TITLE
Should we roll our own proto editor?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#11]
I spent most of the day trying to mock up a visual editor for Reaction protos. Unfortunately, the complexity of the schema (mostly due nested repeated messages) makes it impractical to use colab and/or jupyter widgets. I also tried to use some existing tools like [letmegrpc](https://github.com/gogo/letmegrpc) but didn't have any luck.

Our primary goal here (I think) is to make it easy for people to understand the schema and assess its completeness and usability. *I think it should be a non-goal to build a GUI that people can use to create protos*, since programmatic approaches will be less error-prone and much more scalable. (Also, good UX is hard.)

As such, I suggest that we do two things in lieu of building a GUI editor:
1. Generate good documentation that makes it easy to see the whole schema at a glance (see #10 for a start).
2. Provide some specific Python examples of populating reactions with varying degrees of complexity so people can see how the schema will be used in practice. We could also generate visualizations of these examples if needed.

What do you think?

**Comment by connorcoley** [comment]
I was concerned about the nested repeated messages complicating things (more so after seeing you open the issue re: solvents and supports for compound amounts). 

I agree that programmatic approaches may be less error-prone. For adoption by HTE practitioners, programmatic is fine. However, a traditional bench chemist is unlikely to programmatically define a proto. 

Is creating a GUI for this the kind of thing that a front-end developer could make in an afternoon (if not restricted to Colab/Jupyter, of course)?

**Comment by connorcoley** [comment]
I should add that your 1 and 2 are good to do regardless and may be sufficient for the first stages of stress testing the schema.

**Comment by skearnes** [comment]
Thanks, I think this makes sense and that it would be relatively easy for a skilled developer to make something quickly. I've started a [requirements doc](https://docs.google.com/document/d/1O8xW3amorbFQZR_Iirj1CMXRoobeyikelL7VNktjrik/edit?ts=5e4c20b6#) for the interface.

**Comment by connorcoley** [comment]
LGTM. 

For your point 2, is there any benefit to defining a certain number of examples as .json files that can be parsed into the schema after compiling? Or should examples be prepared only using pure Python?

**Comment by skearnes** [comment]
We could include both if you think they will both be useful. Note that JSON can be parsed directly with [json_format](https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html#google.protobuf.json_format.Parse).

**Comment by connorcoley** [comment]
We can focus on the programmatic definitions and then generate the json from the messages

**Comment by connorcoley** [comment]
If you illustrate 1-2 examples in a Colab or Jupyter notebook, I can work on preparing some others. I had originally intended for us to exhaustively extract reactions from the papers I uploaded, but maybe that is too ambitious for now.

**Comment by skearnes** [comment]
Sure, I can do that.

**Comment by skearnes** [comment]
I'm going to mark this as closed since we've decided on a course of action here.
