### ISSUE TITLE
Possible enhancements to Dataset

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#110]
* `doi`: we could assign a DOI to each submitted dataset that could be used to reference the dataset in publications.
* `url`: pointer to the dataset in the official repository.
* `version`: integer version number that would be incremented any time the Dataset or one of its Reaction messages is updated.

**Comment by connorcoley** [comment]
> `doi`

Got it -- probably good to leave out of the schema for now until we figure out how that process would work. I would love to get citable DOIs for HTE datasets. I don't know how we would handle situations where a dataset only has a few reactions (or just one).

> `version`

I could see some version of the `repeated RecordEvent record_modified` provenance we use for reactions also applying to datasets.

**Comment by skearnes** [comment]
Revisit later: consider a `dataset_doi` field.
