### ISSUE TITLE
Molecular canonicalization

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#130]
We will likely want to perform some canonicalization workflow. Ideally, the primary format in which structures are defined will be SMILES (user-created, copied from ChemDraw, automatically generated from a web drawing tool, etc.). What post-processing, if any, should be performed?

[MolVS is now integrated into the RDKit](https://www.rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html), so it would be straightforward to use that code directly. See an example for tautomers [here](https://rdkit.blogspot.com/2020/01/trying-out-new-tautomer.html). 

Removing metals, salts, changing charges, etc. are all fairly "dangerous". For example, using the `import rdkit.Chem.MolStandardize.rdMolStandardize.StandardizeSmiles`, which applies all of the corrections, converts neutral metals to ions (e.g., `[Mg]` is resolved to `[Mg+2]`. Identifying the parent tautomer may be safer, but I haven't identified all of the potential bugs (e.g., [stripping stereochemistry](https://github.com/rdkit/rdkit/issues/2363))

I am satisfied leaving the current code as-is, where a SMILES string is parsed into the RDKit and dumped to a `RDKIT_BINARY` identifier type. When we set up database searching and other visualization tools, we can think about what to add. 

(I'm leaving this issue open as a reminder to ourselves to discuss this periodically)

**Comment by skearnes** [comment]
Decision: don't edit what users submit; possibly do canonicalization in export to BigQuery etc.
