### ISSUE TITLE
Printing default units

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#15]
Not printing enums at their default value isn't a big issue except for units. Should we add an "unknown" to each unit so that when the field is set, it prints?

See https://github.com/protocolbuffers/protobuf/issues/2871

This came up in the recent example for reaction time. If the units are hours, the units field won't print.

**Comment by skearnes** [comment]
Ah, now I see the reason for the new defaults in #14. SGTM.

**Comment by skearnes** [comment]
Reopening to allow #14 to close it.
