### ISSUE TITLE
Can multiple datasets use the same reactions?

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#150]
Suppose we have a handful of publications, where each has a `Dataset` with all of the reactions contained in that publication. Now suppose someone comes along and wants to create an "All C-N cross couplings reactions from 2019" `Dataset`. Is that an appropriate use case? Do we allow the creation of these aggregated datasets?

If no, let's make sure we aren't neglecting this possible use case of curating data subsets.

If yes, let's think about how to avoid storing redundant information and how we might link both datasets to the same reaction IDs.

**Comment by skearnes** [comment]
My first thought is "no", and I was thinking that people could group together multiple datasets on their own if they wanted to---just a list of dataset IDs. But this leaves out the case of taking a subset of a dataset.

My second thought is that `Dataset` is primarily for grouping protos together for managing git, and the logical grouping is also an important consequence. For subsets/supersets, we might want to consider adding a field to `Dataset` (or possibly a new message) that stores `repeated string reaction_ids` so the data wouldn't need to be replicated for these cases. We could provide a simple utility for extracting all the listed reactions into a new `Dataset` outside of the repo. Thoughts?

**Comment by skearnes** [comment]
The recommendation for repeated `oneof` is to use parent message, something like:

```proto
oneof kind {
  ReactionList reactions = 1;
  ReactionIdList reaction_ids = 2;
}
message ReactionList {
  repeated Reaction reactions = 1;
}
message ReactionIdList {
  repeated string reaction_ids = 1;
}
```

but that introduces a stutter. Alternatively you could do something like:

```proto
message DatasetEntry {
  oneof kind {
    Reaction reaction = 1;
    string reaction_id = 2;
  }
}
repeated DatasetEntry entries = 1;
```

and we would need to check for consistency in the `kind` for each entry. I kind of like this option because it puts a bit more of the logic into the schema instead of the validations, but I'm also ok with just adding a `repeated string reaction_ids` field and using validations to check.

Thoughts?

**Comment by connorcoley** [comment]
I'm not a fan of the first option because of that extra `.reactions` layer.

For the second option, this would mean you can no longer construct a dataset using `reactions=my_reactions`, right? You would need to use `entries=[DatasetEntry(reaction=rxn) for rxn in my_reactions]`?

I think adding a `repeated string reaction_ids` field might be confusing at first, but we can try to make it clear that this should _only_ be used if the dataset does not contain any reactions itself. I would support this option, where validations are used to check. 

I also think it will probably take quite some time before we have contributed datasets that are slices of other datasets in the repo :)
