### ISSUE TITLE
Potential duplicate information in Analysis and yield

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#16]
One ```analysis``` entry might be present as part of a ReactionAnalysis but could also be what was used to quantify yield. Right now, the yield analysis method is cross-referenced with the ReactionAnalysis enum, but it's missing all of the extra fields (e.g., a string field with additional details, raw spectra, etc.). It's almost like we want to cross-reference how the yield was quantified with a full ReactionAnalysis, not just the type.

**Comment by skearnes** [comment]
I agree; I don't really like the `ReactionAnalysis.AnalysisType` and it seems like a raw `ReactionAnalysis` would be more complete.

**Comment by skearnes** [comment]
maybe rename to `yield_analysis`?

**Comment by connorcoley** [comment]
If we convert to a ```ReactionAnalysis yield_analysis``` then, are we now being inconsistent w.r.t. ```conversion``` since that doesn't get linked to a full analysis? 

One analysis can produce multiple readouts (yields of multiple products, conversion, etc.). 

It's almost like product yields/identities should theoretically be a sub-field within an analysis, but I don't like the idea of burying information so deeply

**Comment by skearnes** [comment]
Maybe we should remove `yield_type` entirely and just push these details into `ReactionOutcome.analyses`? That would remove the extra level of nesting.

**Comment by connorcoley** [comment]
I'll have to think about this more. In the case where there are multiple analyses, it's useful to know how the experimentalist arrived at the yield. Each experiment might have a crude HPLC and NMR, but the yield could still be an isolated yield.

**Comment by skearnes** [comment]
I think I'm still leaning towards adding a full `Analysis` to `ReactionOutcome`. This would avoid the awkward nested reference to `ReactionAnalysis.AnalysisType`.

**Comment by skearnes** [comment]
(It would also make #38 a bit cleaner.)

**Comment by connorcoley** [comment]
I don't think we can universally say that an Analysis should be a subfield of ReactionOutcome though. A reaction can have multiple analyses, where one or more were used to identify the product(s) or product yield(s) and selectivity(s). One Analysis could be used to quantify multiple products, and I don't think we would want to encourage recording the same Analysis for multiple Outcomes.

**Comment by skearnes** [comment]
I think I mistyped my last comment; I agree that Analysis shouldn't be owned by ReactionOutcome. I think I meant to say that I support adding an Analysis field to ReactionProduct instead of just AnalysisType.

**Comment by connorcoley** [comment]
What would the "best practices" be in the following cases:
- One set of analytical data to quantify the yield of two products as well as the conversion (e.g., a single HPLC run where we have calibrated standards or multiple peaks)
- One product whose identity and purity were confirmed by NMR but whose yield was determined by an isolated weight
- One product whose identity and yield were both determined by NMR, the sole analytical technique reported

**Comment by connorcoley** [comment]
Is this a case where a map would make sense?

In ```ReactionOutcome```: ```map<string, ReactionAnalysis> analyses```
In ```ReactionProduct```: ```string identity_analysis```, ```string yield_analysis```, ```string purity_analysis```, ```string selectivity_analysis```

where the string values in ```ReactionProduct``` are intended to correspond to the keys used for the analyses. This couldn't be enforced by the schema, but could be enforced by a validation script. This would let us indicate _which_ analysis was used to derive which property/datum.
