### ISSUE TITLE
Automatically parse strings like "120 uL" into appropriate unit/value fields

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#18]
I can take the first pass at this; it will be the start of our thin python layer to make interacting with the schema easier for most users.

**Comment by connorcoley** [comment]
I have some basic code in the Colab notebook for you to work from

**Comment by skearnes** [comment]
I like what you did in the notebook. Regarding your question about defining the unit lists in the schema itself, I played with that a bit and I think I'd prefer to keep it separate.

- Having it as part of the schema would require us to populate a global variable programmatically, which I would really like to avoid. I'd much prefer a module-level constant similar to what you put in the notebook. (See http://google.github.io/styleguide/pyguide.html#25-global-variables.)
- I think it might be cleaner and easier to maintain if we keep the underlying schema separate from the "translation" layer. These unit names are not part of the schema, they are part of the translator.

Thoughts?

**Comment by connorcoley** [comment]
I agree that keeping it separate makes sense, so long as the "translation" code is part of this repo still (but not the ```.proto``` itself)

**Comment by skearnes** [comment]
Yes, for sure.
