### ISSUE TITLE
Colab links in example notebooks point to skearnes fork of repo

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#193]
Colab badge link in this repo ([here](https://github.com/Open-Reaction-Database/ord-schema/blob/master/examples/2_Nielsen_Deoxyfluorination_Screen/example_nielsen.ipynb )) opens a notebook using @skearnes's fork of the repo ([here](https://colab.research.google.com/github/skearnes/ord-schema/blob/master/examples/2_Nielsen_Deoxyfluorination_Screen/example_nielsen.ipynb)) instead of Open-Reaction-Database

**Comment by connorcoley** [comment]
Actually, it seems like we have a bigger problem with the Colab notebooks since they aren't installing a recent enough version of `protobuf` and we now require `rdkit` to use validations.

**Comment by connorcoley** [comment]
See fb639b0 for a potential fix that creates a conda environment and installs RDKit within the Colab notebook if they can't be imported. PTAL and I can patch the other notebook examples.

**Comment by skearnes** [comment]
That commit looks reasonable; I wish there was an easier way to deploy code snippets like this. (Note that `chmod +x` shouldn't be needed since you're running it with `bash` instead of executing it directly.)

**Comment by skearnes** [comment]
The pointers were fixed in #209; I think we can close this?
