### ISSUE TITLE
Re-enable editor tests

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#199]
#198 disabled `test_editor` in the CI workflow pending support for optional fields in JS proto wrappers. It needs to be re-enabled when the next minor release of protobuf is cut, or when we build and deploy our own `protoc` at HEAD.

**Comment by antonkast-google** [comment]
PR #207 adds the needed protoc binaries and matching protobuf JS runtime files for x86-64 Mac and Linux.

It also moves the editor dependencies on generated python files to the "build" directory, so there will be no more ambiguous python namespaces.

It does not reenable the CI workflow though. I don't know how to do that.

**Comment by skearnes** [comment]
Thanks; you can uncomment the test in this file in your PR: https://github.com/Open-Reaction-Database/ord-schema/blob/master/.github/workflows/run_tests.yml#L70
