### ISSUE TITLE
Documentation regarding proto3 use

### ISSUE THREAD

**Issue by mc-robinson** [Open-Reaction-Database/ord-schema#21]
Hi, @alphaleegroup recently pointed me to this project. I am quite interested in the topic and would potentially be interested in helping, if you all were open to other contributors. 

I was briefly looking over the Github, trying to learn more about the data structure. I found a bit of documentation in the comments of the `proto/ord-schema.proto` file, but I was wondering if there was more documentation anywhere? In particular, I have briefly skimmed https://developers.google.com/protocol-buffers/docs/proto3, but I am not sure I fully understand the use of proto3. It would be greatly appreciated if you could maybe explain the advantages of its use in comparison to other approaches such as a JSON format or XML (or chemical markup language). I have also come across Autoprotocol (http://autoprotocol.org/ open-sourced by Transcriptic), which seems adaptable to chemistry, since it is useful for precisely defining experiments in biology.

Thanks, I look forward to learning more, and please do let me know if there are ways I can help.

**Comment by skearnes** [comment]
Hi, thanks for your message. Please see this page for more info on the choice of protocol buffers: https://developers.google.com/protocol-buffers/docs/overview#whynotxml

We are currently in the process of writing some examples to show the usage of the protocol buffer schema; please stay tuned for more to come in the future along with opportunities to provide feedback on the database. You might consider joining the mailing list: https://groups.google.com/forum/#!forum/open-reaction-database.
