### ISSUE TITLE
Floating point errors when loading/saving in editor

### ISSUE THREAD

**Issue by n8kim1** [Open-Reaction-Database/ord-schema#229]
**Describe the bug**
In the editor, floating-point errors occur when loading or saving a float value.

**To Reproduce**
Loading a float value:
1. Load a reaction in the editor
2. Set a value to 0.1
3. Save the reaction (note that it's correct in the pbtxt file)
4. Load the reaction again
5. See the value textbox be filled with a float that's not exactly equal to 0.1

Saving a float value:
1. Load a reaction in the editor
2. Set a value to 0.1212121212
3. Save the reaction (note that it's truncated in the pbtxt file)
4. Load the reaction again
5. See the value textbox be filled with a float that's not exactly the original value nor truncated value

**Expected behavior**
While the loss of precision isn't an issue, the extra digits in the editor's value may be jarring.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium 83, JS 8.3, Python 3.7.6 (Conda 4.8.3)

**Some thoughts**
Various conversions occur in a few places. Strings of digits are converted to floats when a protobuf message is created, both during loading (in the backend) and saving (in the frontend); I assume errors can't be avoided here. On the other hand, when the backend writes to the text file, only 8 digits are saved -- a setting we could change. (see [backend code](github.com/Open-Reaction-Database/ord-schema/blob/main/editor/py/serve.py#L326), [`float_format` arg in protobuf API docs](googleapis.dev/python/protobuf/latest/google/protobuf/text_format.html#google.protobuf.text_format.MessageToString) )

If this issue is worth fixing, what would be best? 
I'm thinking that when the frontend loads, it could round every float (for example to 8 digits, to match with the backend). Or, when the backend saves a reaction, it could write more digits than just 8.

@antonkast-google @skearnes @connorcoley

**Comment by antonkast-google** [comment]
The editor uses the DOM as its data model. So going round-trip from proto to UI and back to proto must pass through a textual representation. This loses information.

The current implementation minimizes this loss by showing all the decimal places, which is surely jarring for users as roundoff errors can add a lot of decimals.

+1 for adding precision in the pbtxt representation. I didn't know that was possible.

An alternative could be to declare that the ORD limits floats to a human-friendly number of significant digits, then do controlled roundoff at every translation.

**Comment by skearnes** [comment]
+1 for rounding; I've done this for other projects.

**Comment by skearnes** [comment]
We decided that anything we do here is likely to cause more problems than it fixes, especially on the backend.

**Comment by skearnes** [comment]
Reopening since this came up for one of our alpha testers.

**Comment by skearnes** [comment]
![image](https://user-images.githubusercontent.com/952729/93810313-afa6b780-fc0b-11ea-97a3-cf9b921914ef.png)

**Comment by skearnes** [comment]
![image](https://user-images.githubusercontent.com/952729/93810398-d533c100-fc0b-11ea-8b66-c89333b1a365.png)

(on reload after entering 0.04 and 0.01)

**Comment by skearnes** [comment]
Note that the pbtxt is correct:

```
moles {
  value: 0.04
  precision: 0.01
  units: MILLIMOLE
}
```

**Comment by skearnes** [comment]
https://stackoverflow.com/a/3644302: a quick fix is to use `toPrecision(7)` since the underlying protos are encoding 32-bit floats

**Comment by skearnes** [comment]
Note that using `<input type="number"...>` instead of `contentEditable` provides free input validation...
