### ISSUE TITLE
Migrate to latest protobuf release

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#266]
https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.4 has been released, so we no longer need to build and distribute our own library to get access to the JS `optional` support.

https://github.com/Open-Reaction-Database/ord-schema/blob/f09ca244c60206b06aa32e24b491cda07ac963f1/.github/workflows/run_tests.yml#L93-L94

**Comment by antonkast-google** [comment]
The tarball provides more than just the protobuf JS runtime. It also provides the protoc compiler where --js_out has been updated to support proto3 optional.

If we remove the tarball, then we will have to introduce a step to compile protoc. What are the prospects for getting an updated protoc from the python environment?

**Comment by antonkast-google** [comment]
Here is a draft of the change to remove the tarball dependency, in case anyone wants to try out a protoc update.

https://github.com/Open-Reaction-Database/ord-schema/pull/268

**Comment by antonkast-google** [comment]
Our protoc-wheel-0 package is now at version 3.13.0, so it supports "optional" declarations with --js_out. This means we can abandon the tarball and use the original 3.13.0 protobuf release files to provide our JS runtime.

I have updated #268 to abandon the tarball, use protoc from the pip environment, and use the official protobuf distribution for the JS runtime files.
