### ISSUE TITLE
Should reaction role be moved to "compound" from "reactioninput"?

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#27]
When modifying the example of a pre-mixed stock solution, I started to confuse myself as to the ```reaction_role``` and ```is_limiting``` fields of the ReactionInput. My inclination is to move these two fields to be part of the ```Compound``` message, since we should separately specify the role and is_limiting of different solutes or solvents.

Now, this makes things a little funny because the solution-level compound message won't have a defined role, whereas the pure solute-level and solvent-level compound message will. 

In keeping with the spirit of making the schema as closely aligned with a chemist's actions (or a robot's actions), what if we more strictly treat the ```ReactionInput``` as something that is added to the vessel? What I might propose is the following:

- A ```ReactionInput``` contains a ```repeated Compound components``` field that is _always_ populated. A ReactionInput can be a pure substance (with a single components message) or a mixture (with multiple components messages).
- We do not give ```ReactionInput``` messages their own ```amount``` field. A reason to consider adding one would be if the ```components``` define a large-scale stock solution and we just want to change the amount of that solution that is added for a particular reaction. However, I think this might introduce too much complexity; it could be better to force each component compound's amount to be the actual amount that was added.
- ```Compound``` messages now contain fields for ```reaction_role``` and ```is_limiting```. A compound is always a pure substance. We no longer have nested compound messages.
- ```ReactionInputs``` are given a ```string description``` field; this is for convenience and bookkeeping only and could be omitted. If a pure substance, the description could be the name of its sole component, like "24 mg of XPhos". If a stock solution, the description could be a text description like "125 uL of 4 M NaOH in water". A lightweight parsing tool with basic regex could potentially be used to fully populate the ```components``` field given this description, if so desired.

Thoughts?

**Comment by connorcoley** [comment]
Re: giving ```ReactionInputs``` an ```amount``` field, I think this is necessary for flow chemistry...

**Comment by skearnes** [comment]
A huge +1 to removing nested `Compound` messages. I'll review #28 and add any additional comments there. Thanks!
