### ISSUE TITLE
Compilation used for JS linting doesn't properly import

### ISSUE THREAD

**Issue by n8kim1** [Open-Reaction-Database/ord-schema#277]
Unfortunately our JS linter tries to compile improperly, and errors during CI. I got sick of this and tried to fix it -- couple of attempts [here](https://github.com/Open-Reaction-Database/ord-schema/tree/lint-js-fix) and [here](https://github.com/Open-Reaction-Database/ord-schema/tree/lint-js-fix-2). However, there's still an issue.

In short, _I think the compilation process used by the linter's compiler is not the proper process to build our code. This prevents the compiler from finishing -- let alone the linter from linting all our code._

The Closure compiler used in CI/linting can't build our code. It doesn't like the `goog.require(proto.ord.*)` imports, and errors, saying that "Required namespace `proto.ord.*` never defined." The compiler is right: it's building `editor/js`, our human-written js code, and we never define these namespaces here. Instead, the namespaces are created during the editor's build process, and are present only in `editor/gen` (which we serve from). Ultimately, our built code doesn't have import issues -- our source code just appears to have them.

How can we lint in a way that the linter would like? Can we make the linter ignore / warn for `JSC_MISSING_MODULE_OR_PROVIDE`, rather than throwing an error, and skip over these imports? (I don't think it would be a good idea to lint generated code...)

@skearnes @antonkast-google

**Comment by skearnes** [comment]
Right now the linter is looking at all the JS files at once, which could be part of the issue. But I think looking at individual files is the cause of the import errors you're seeing. Maybe there's a couple of groups of files that should be in different directories or something?

**Comment by skearnes** [comment]
Ah I see that's what you tried in your first change; hmm....

**Comment by skearnes** [comment]
I'd recommend fixing as much as you can first, and then we can dig deeper into what remains. I'm seeing 244 warnings now and that makes it a bit hard to debug issues with the linter itself...

**Comment by n8kim1** [comment]
Sounds good. Nearly all the warnings are about adding documentation; I'll clean up the other warnings first. 

I don't think the remaining documentation warnings should interfere with the errors. (also, the documentation would take a while to write)

**Comment by n8kim1** [comment]
I did some more digging and updated/clarified the original issue description. As far as I can tell, the problem is that we import lots of generated code, but don't expose this generated code to the linter...
