### ISSUE TITLE
Add precision to all measurement types?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#29]
`Amount` currently has a `precision_in_percent` field. How would you feel about adding a precision field to all of the measurement types and removing this one?

* The precision would be closer to the value.
* There may be precision information for non-`Amount` measurements, such as voltages or flow rates.
* (optional) This would allow us to remove the nesting that stills bugs me in `Compound`, since `Amount` could be replaced with the `oneof` it currently wraps (we would change the oneof name to "amount" from "kind" for programmatic extraction of set values).

**Comment by skearnes** [comment]
Related: should the precision be in percent or standard deviation of the value type? SD is nice because it has the same units and (may) be easier to compute.

**Comment by connorcoley** [comment]
+1 for having precision be a separate field for all measurements. Those are great justifications. The ```precision_in_percent``` field should be changed to ```precision``` and the documentation should note that it's in the specific units of the measurements, NOT as a percentage.

Another location where we would want to define precisions is for conversions and yields (```conversion_in_percent``` and ```yield_in_percent```). What do you think about defining another measurement-type ```Percentage``` with ```value``` and ```precision``` fields? So it's like a measurement but w/o the ```units```. We could then simplify these fields to ```Percentage conversion``` and ```Percentage yield``` and remove the ```yield_precision_in_percent``` field, which is the worst name.

I kind of like having the ```amount``` field, but I do see how it might be better to remove an additional level of nesting.

**Comment by skearnes** [comment]
> +1 for having precision be a separate field for all measurements. Those are great justifications. +1 for changing the `precision_in_percent` field to `precision` and the documentation should note that it's in the specific units of the measurements, NOT as a percentage.
> 
Great, I'll send a PR.

> Another location where we would want to define precisions is for conversions and yields (`conversion_in_percent` and `yield_in_percent`). What do you think about defining another measurement-type `Percentage` with `value` and `precision` fields? So it's like a measurement but w/o the `units`. We could then simplify these fields to `Percentage conversion` and `Percentage yield` and remove the `yield_precision_in_percent` field, which is the worst name.
> 
Yes, I like this; I'll include it in the PR.

> I kind of like having the `amount` field, but I do see how it might be better to remove an additional level of nesting.
I'll add it to the PR and you can see how you like it in that context. With these changes `Amount` will simply be a wrapper around a oneof, so I think it makes sense to remove the extra layer.
