### ISSUE TITLE
Fix JS warnings

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#293]
The current JS linter uses `--jscomp_warning` and doesn't fail on (many) warnings. I'd like to change this to `--jscomp_error`.

**Comment by n8kim1** [comment]
@skearnes #295 simply changes from `--jscomp_warning` to `--jscomp_error`, and now throws an error on any warning (we have over 200, whoops). Would this be good?

**Comment by skearnes** [comment]
Yep, I just didn't want to break the CI again until you've had a chance to fix the warnings :)

**Comment by n8kim1** [comment]
Ah I see, thanks! (The issue name makes a lot more sense now)

**Comment by connorcoley** [comment]
@n8kim1 I won't complain if you want to help fix some of these ;) we can both work off of the lint-js-err branch asynchronously

**Comment by n8kim1** [comment]
There's only three different kinds of problems the linter has: JSDocs, semicolons, and Closure imports/exports. I'd rather turn the Closure issue into its own issue/PR, because fixing it might be a bit hairy...

**Comment by connorcoley** [comment]
I know nothing about Closure so I will defer to you and/or Anton on that

**Comment by skearnes** [comment]
It's also fine to submit multiple PRs to fix different things---no need to mash it all into a single PR.

**Comment by n8kim1** [comment]
Sounds good, thanks guys!

(FYI #297)

**Comment by skearnes** [comment]
Hi @n8kim1, what's the status on this? Are we ready to make these warnings into errors?
