### ISSUE TITLE
Auto-collapse existing repeated messages when adding another element

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#294]
When I was watching Connor's excellent tutorial video, I thought that the readability of the form might be improved if existing repeated fields were collapsed when adding new elements. For example: (1) collapse the previous input(s) when adding a new input or (2) collapse the previous component(s) when adding a new component.

**Comment by connorcoley** [comment]
After further discussion, decided that this wouldn't necessarily be an improvement to the UI
