### ISSUE TITLE
Correct place for unit definition

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#3]
Should the units expected of each field be defined (a) in a comment, (b) in the name of the field, or (c) in a separate enum to allow users to define values however they would like?

**Comment by skearnes** [comment]
My preference is for (a) and (b). This provides a couple of advantages:
* When the unit is part of the variable name, it makes it easier for people to remember which units to use.
* If we force people to use a single unit, we can avoid having to do conversions to a common unit for e.g. searching and it will reduce the complexity of the API/schema overall.

**Comment by connorcoley** [comment]
One concern I have is whether manual entry might result in incorrect unit conversions. If we let people select units from an enum, we can at least simplify conversions in some validation/standardization script. Time (hours / minutes / etc.) is fine, but I have slightly less confidence in manual conversions of temperature (F / C) and pressure (bar / psi / atm).

**Comment by skearnes** [comment]
That's a good point. I'm still worried about the complexity of an extra enum; what if instead we used a oneof with a couple different units that we expect? Then the variable names would still be explicit.

For example:
```
oneof pressure {
  float pressure_in_bar = 1;
  float pressure_in_atom = 2;
  float pressure_in_psi = 3;
}
```
What do you think?

**Comment by connorcoley** [comment]
I recognize the clarity of having units in the field names to avoid any ambiguity, but it feels sloppier to me than having ```pressure_value``` and ```pressure_units``` fields. I'm not as clear on the downside of having too many enums. Being able to extend the schema to handle different/new units by adding options to a single enum seems better to me than extending a oneof.

**Comment by skearnes** [comment]
OK, let's give enums a try.
