### ISSUE TITLE
Add time to all measurement types?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#31]
Related to #29:

Should we consider adding a `Time` field to all measurement types? This would avoid some of the composition we do elsewhere, as in `TemperatureConditions.measurement`, but may not make sense if most measurements don't have time values (e.g. `Compound.mass`).

I don't have strong feelings on this one, but I wanted to bring it up for discussion.

**Comment by connorcoley** [comment]
My opinion is no. It feels clean enough to have measurement data effectively be a list of (time, value-with-units-and-precision) tuples.

**Comment by skearnes** [comment]
SGTM.
