### ISSUE TITLE
Field "yield" creates Python error 

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#33]
The ```yield``` field of a reaction product leads to a syntax error when trying to access it. Thoughts on a replacement field name?

**Comment by skearnes** [comment]
Wow, that's annoying. You'd think protoc would complain about reserved word conflicts.

Do `yield` and `conversion` convey the same information? We have a top-level `conversion` value in `ReactionOutcome`; is that all we need?

**Comment by connorcoley** [comment]
Unfortunately they don't, and there is no substitute for the word "yield". Maybe we can replace the block 

```
Compound compound = 1;
  bool is_desired_product = 2;
  Percentage yield = 3;
  ReactionAnalysis.AnalysisType yield_type = 4;
```

with

```
Compound compound = 1;
  bool is_desired_product = 2;
  Percentage compound_yield = 3;
  ReactionAnalysis.AnalysisType compound_yield_type = 4;
```

Not ideal, but a quick fix

**Comment by skearnes** [comment]
+1 (don't forget yield_type_custom)
