### ISSUE TITLE
Batch processing for large dataset enumerations

### ISSUE THREAD

**Issue by n8kim1** [Open-Reaction-Database/ord-schema#334]
Outline/ideas from Anton: "I heard from Steven that a reaction template operation takes over 30 seconds to process 5,000 rows. That's getting too long for HTTP, so I think optimization makes sense.

First I would make sure you understand what scale we should aim to support (how many rows per operation, how many string substitutions per row). Then I would see how long that really takes and make sure we're not doing anything inefficient that could be fixed in a simpler way. You may want to benchmark on our VMs. That will require a login that Steven can set up, but I'd expect the VMs to be comparable to a laptop for python CPU.

I imagine a new web page where you can quickly upload your template and your table. These will immediately get written to a designated part of the server file system, like a special subdirectory of db/, and the page shows you what you've uploaded in a list. Each entry has a status, like "in process" or a percentage or "processed", and the entries update periodically, like by polling.

Our python server is single-threaded, so you can't use it to do the background work. I would write a script that scans the special subdirectory for eligible work, performs the work, writes back its progress to the same directory, and quits when it's done. The script is started as a subprocess from the new web page, and it can be retriggered by a button like "reprocess". The important thing is that the user's uploads are handled in the simplest possible way and the workflow is idempotent. Then when we mess up (background process crashes, a bug in the script, whatever), we can always reprocess and all is forgiven."

**Comment by skearnes** [comment]
As a short term solution, we are planning to increase the worker timeout in the web server. Moving to e.g. 2 minutes should cover most cases and any remaining exceptions can be handled in coordination with the ORD reviewers.

**Comment by antonkast-google** [comment]
Would this processing block serving?

**Comment by skearnes** [comment]
I think we can avoid blocking by using multiple worker processes and/or threaded workers. Threaded workers explicitly allow us to sidestep the timeout issue: "One benefit from threads is that requests can take longer than the worker timeout while notifying the master process that it is not frozen and should not be killed."

https://docs.gunicorn.org/en/stable/design.html#how-many-threads

**Comment by skearnes** [comment]
This can be done offline in coordination with reviewers, so not a critical feature. Closing for now.
