### ISSUE TITLE
How to cite this database?

### ISSUE THREAD

**Issue by zguo235** [Open-Reaction-Database/ord-schema#338]
Hi,

This is a very important project for this research field. I want to cite this database in my paper. I checked the document but didn't find the authors of Open Reaction Database.

Can anyone tell me how to cite this database?

Best,

Zhongliang

**Comment by skearnes** [comment]
Hi Zhongliang, thanks for your question. We're still in the alpha testing phase, but we plan to release a citable whitepaper for the ORD after the official launch. In the meantime, it's probably best to cite https://open-reaction-database.org. You can use "Open Reaction Database Project Authors" as we do in the headers for the source files in this repo.

The project also has a [Governing Committee](https://docs.open-reaction-database.org/en/latest/overview.html#governing-committee) and [Advisory Board](https://docs.open-reaction-database.org/en/latest/overview.html#advisory-board).

**Comment by zguo235** [comment]
Thanks for the prompt reply. I will use "Open Reaction Database Project Authors" for the citation. Hope to see the release of this database in the near future.
