### ISSUE TITLE
ord.dataset.init()

### ISSUE THREAD

**Issue by antonkast-google** [Open-Reaction-Database/ord-schema#340]
Commit 8f3d4687de8 altered the body onload function in dataset.html without renaming the function itself, breaking page initialization. https://github.com/Open-Reaction-Database/ord-schema/pull/297

**Comment by antonkast-google** [comment]
Or perhaps I'm running the editor incorrectly? In the Conda environment, after setup.py, I run editor/serve.sh, load http://localhost:5000/dataset/dataset, and observe

Uncaught TypeError: ord.dataset.init is not a function
    at onload (dataset?user=...)

**Comment by n8kim1** [comment]
That's weird, it works for me... Just to check, have you rebuilt dataset.js / re-run the editor makefile? I'll dig some more.

**Comment by antonkast-google** [comment]
My problem was fixed by a clean make. Thanks!
