### ISSUE TITLE
Editor does not reload compound drawings

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#344]
When I click a previously defined reaction on the Dataset page, the reaction loads without rendering the images for the compounds I drew with Ketcher (or that have valid structural identifiers, to be more precise).

**Comment by connorcoley** [comment]
It does for me (both local deployment and at https://editor.open-reaction-database.org/). Do you have a specific example you can point to?

**Comment by skearnes** [comment]
I've tried this using the Dockerfile locally and it fails on every structure I give it; `C1C=CC=C1C` is the latest one.

Note that I'm not referring to the top-level reaction images; I'm talking about the image in the Identifiers section.

**Comment by skearnes** [comment]
It doesn't seem to repro online though...huh

**Comment by skearnes** [comment]
I'm seeing this again with the current live editor. The image appears for a moment when the page is loading and then disappears.

**Comment by skearnes** [comment]
https://editor.open-reaction-database.org/dataset/dataset/reaction/0?user=aa29c12389b846e9bf6a1050710002d4

**Comment by connorcoley** [comment]
I can see the error when loading the page >50% of the time now, thanks. I wonder if this is related to the order/speed of loading page elements. I noticed that the [delay for validating the reaction](https://github.com/Open-Reaction-Database/ord-schema/blob/main/editor/js/reaction.js#L99) has been removed but perhaps adding it back would fix this. Could the reaction-level validation be finished before the component's fields are added and populated on the form?

**Comment by antonkast-google** [comment]
I strongly advise against solving this problem with setTimeout(). There is no way to control how long validation takes on the server.

I think the bug is the intermittency. I don't know how these images are supposed to initialize, but it should be deterministic.

**Comment by connorcoley** [comment]
The uncertainty isn't around how long validation takes on the server, but how long `loadReaction` takes on the client side. Does that change your consideration at all? I think what is happening is that `validateReaction` is being called before the reaction is fully loaded.

**Comment by n8kim1** [comment]
After some discussion, for the alpha release, we'll increase the timeout for now -- 1000 seems to be fine.

We'll try to find a clean solution down the road.

**Comment by n8kim1** [comment]
With the changes to using svg's, does this error still occur? I can't reproduce it (and I can see why it might be fixed).

**Comment by skearnes** [comment]
No longer showing up; this seems to be fixed by the move to SVGs (and not using an empty `src` attr in the HTML).
