### ISSUE TITLE
save action on invalid reaction fails silently

### ISSUE THREAD

**Issue by antonkast-google** [Open-Reaction-Database/ord-schema#346]
Open the "full.pbtxt" test case in the reaction editor. Hit "save". Observe that "saving" remains visible indefinitely and the JS console shows an uncaught exception.

If saving an invalid reaction is illegal, the user should see an error message. I would prefer though that save always work.

**Comment by connorcoley** [comment]
This seems to work fine for the main branch and the editor site for me; was this on a local deployment or on the public editor?

**Comment by skearnes** [comment]
(Note that using the Dockerfile is the best way to make sure you have a clean build.)

**Comment by antonkast-google** [comment]
Sorry! My mistake. This does not reproduce when I run from the Docker environment.

I am addicted to running without Docker because I can iterate without "docker build", which takes me half a minute. Also I am observing intermittent long page loading latencies under Docker on my MacBook, seemingly about 30 seconds for the initial response on every other request.

I'd love any advice on good workflow.
