### ISSUE TITLE
Question about int/float differentiation for Data messages

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#357]
Copied from https://github.com/Open-Reaction-Database/ord-schema/issues/349#issuecomment-691330348:

> @connorcoley my solution in #350 is to look at the value in the text field and, if it can be parsed as an integer, use integer_value instead of float_value. This means that even numbers entered as e.g. 140.0 will be converted to integer_value in the Data message.
>
> Is this what we want? Or do we want to expand the number radio button to float and integer?

**Comment by connorcoley** [comment]
I think it would be preferable to have "140" be parsed as an int but "140.0" be parsed as a float. Since the user is entering these values as strings, this seems like it should be easy to handle in JS

**Comment by skearnes** [comment]
You're right, we can probably just check for decimal points, etc. Instead of adding another radio button.
