### ISSUE TITLE
TensorFlow dep?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#36]
I'm thinking about ways of storing serialized protocol buffers.

https://developers.google.com/protocol-buffers/docs/techniques#streaming is why things like [TFRecords](https://www.tensorflow.org/tutorials/load_data/tfrecord) and [Riegeli](https://github.com/google/riegeli) exist.

I'd like to use TFRecords for proto serialization, but this requires adding a dependency on TF, at least for the server-side code. Are you okay with this?

**Comment by connorcoley** [comment]
I don't love the idea of having TF as a dependency unless it's only for the centralized deployment of the server. Does it defeat the purposes of using protocol buffers if we serialize data as json?

**Comment by skearnes** [comment]
Not all; proto3 explicitly supports this use case: https://developers.google.com/protocol-buffers/docs/proto3#json (and we can write lots of unit tests to verify this if want).

I agree that JSON is ideal for data exchange, e.g. uploading new submissions to the database. 

For server-side storage/backup/etc., I'd prefer that the "source of truth" on GCP be a binary proto encoding, perhaps stored in bigtable so we get versioning/history info for each entry. This allows for efficient encoding (much smaller) and faster searching (assuming we can make the bigtable proto-aware). But we can iterate on this as we flesh it out.

But yes, let's nix the TF dep for now.
