### ISSUE TITLE
Add a helper for simple solutions

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#372]
An alpha tester reported that encoding multiple simple solutions (e.g. a single solute) was a bit tedious. We might consider adding a "wizard" that allows a user to specify a solute, solvent, and concentration to fill in the relevant underlying parts of the form.

**Comment by connorcoley** [comment]
One option is a quick-add input where we have a basic parser for phrases like `<vol> of <conc> <solute> in <solvent>`
