### ISSUE TITLE
Support reaction templating when some reaction instances are missing a component

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#375]
Reaction templating allows simple string replacements for component identifiers, which is great when enumerating many reactions with, e.g., different ligands. However, a "no ligand" condition cannot be included in the enumeration. We should consider how to support this somewhat common case. Currently, the best workflow involves defining two separate templates, enumerating two separate datasets, and merging them during submission.

**Comment by connorcoley** [comment]
One option might be to detect if a templated field is empty (and allow it). Then, after the message is read, we could look for any components w/o any compound identifiers with non-empty string values and delete the entire compound. This is more involved than just checking for empty messages and deleting them, since there will be other fields within the component that are non-empty.

**Comment by skearnes** [comment]
I think this will be easy as long as we can precisely define the desired behavior. Here's what I'm thinking:

If the templated field is an input compound identifier (with type `SMILES`?), and it is empty, then we delete the entire input.

Does that work for you? This would have allowed me to enumerate the Ahneman dataset without using jupyter, for example.

**Comment by connorcoley** [comment]
Let's also think about weird edge cases that might raise errors. For example, what if a float field is blank in a template cell? Can we actually parse a reaction pbtxt where we have `float_value: `?

**Comment by skearnes** [comment]
> I think that something slightly more sophisticated but along those lines sounds good to me. For example,
> 
> * If after templating, any identifier does not have a defined value, remove the identifier
> * If after that step, a compound doesn't have any identifiers, remove that compound
> * If a compound has an amount explicitly of zero, remove that compound
> * [edit: adding this one] If after these steps an input has no components, remove that input

For the Ahneman case, removing only the compound would leave several inputs with only solvents. I'm not sure of an easy way to say when to remove an input unless we say "all the time" and narrowly scope the use case...

**Comment by connorcoley** [comment]
> removing only the compound would leave several inputs with only solvents

Is it too convoluted to remove the input if (a) prior to checking empty values, there were 2+ components and (b) after removing empty components, there is only 1 component with the SOLVENT reaction role?

**Comment by skearnes** [comment]
I'm guessing that it's the more common case that pure solvent is used when the solute is omitted? In that case, as long as `volume_includes_solutes` is True then I agree with your proposal.

This got me thinking about whether we should be adding pure solvent when no additive is used for https://github.com/Open-Reaction-Database/ord-data/pull/14#issuecomment-707391852.

**Comment by mwleklin** [comment]
Was a solution for this implemented in the web editor? I'm observing errors when trying to enumerate if there is no SMILES information for a ligand and if the amount if set to 0 mmoles it still shows in the schema.
