### ISSUE TITLE
Improve error reporting when dataset enumeration fails

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#389]
Using a placeholder with a space, for example, yields an error that is invisible to the user. Dataset enumeration should be wrapped in a try/except with errors communicated to the user, e.g., through a window alert.

**Comment by skearnes** [comment]
See the error handling for creating a new dataset

**Comment by skearnes** [comment]
Confirm the error codes are right; the HTML is looking for 404 and we're sending 409
