### ISSUE TITLE
Ensure flow tubing material is not redundantly defined

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#39]
Vessels can be tubes with a defined material, but information about the tube diameter and material also appears in the FlowConditions message.

**Comment by skearnes** [comment]
Add a `Vessel` field to `FlowConditions` and expand the `VesselMaterialType` enum to hold the extra values? Also change `Volume vessel_volume` to be `oneof { Volume volume = 1; Length diameter = 2; }`? Or is that too much merging?

Alternatively, we could remove TUBE from Vessel if we always expect tubing to be associated with flow?

**Comment by connorcoley** [comment]
That might be too much merging. Let's wait until we define some flow examples to see what makes sense.

**Comment by connorcoley** [comment]
Let's follow the convention that for flow examples, the `FlowConditions` are the preferred way to define tube material. There is very little redundancy. Defining vessel size in terms of `Volume` and tube diameter in terms of `Length` is appropriate still.
