### ISSUE TITLE
Pick a date where we'll fix the schema

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#40]
Should we set a date for when the first version of the schema will be fixed? I'm worried that we'll never get the examples done if we keep churning things...

Should we wait until we try a few more examples to find all the pain points?

**Comment by skearnes** [comment]
(PS I think the recent changes/churn have all been very good for the schema; no complaints about the process, just wanting to make sure we're thinking ahead.)

**Comment by connorcoley** [comment]
Is March 31 realistic? I want to leave us enough time to define several examples and figure out those workflows, plus write enough Python wrapper code. I'll focus more on the examples.

**Comment by skearnes** [comment]
Yes, end of March is about what I was thinking. Thanks for focusing on the examples; I'm happy to help with wrapper code and I've been doing a lot of GCP work to make sure we're ready.
