### ISSUE TITLE
Don't add +/- comments when both are zero

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#411]
This is confusing since they will be followed up with a more useful comment after the automated update commit. (See https://github.com/Open-Reaction-Database/ord-data/pull/12.)

**Comment by connorcoley** [comment]
Are there ever cases where the change is _actually_ +/- 0 reactions? For example, PRs that just correct an existing entry. Or are these reported as +1/-1?

**Comment by skearnes** [comment]
There could be (they would be 0/0 and not 1/1), but I think it's more confusing to have the 0/0 comments. I suppose we could do something like only post the comment if `process_dataset` is running on something in the `data/` folder...WDYT?

**Comment by connorcoley** [comment]
I think that check would be preferable, since we'll want to keep the real 0/0 comments
