### ISSUE TITLE
Reaction templates

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#43]
A reaction will often be repeated with variations in one or a small number of parameters. We need support for defining a template and using it to describe multiple reactions.

(creating the issue as a reminder to myself)

**Comment by skearnes** [comment]
@connorcoley has done some initial work in this area; close this issue when we commit an example to this repo.

**Comment by connorcoley** [comment]
Between the [Nielsen example](https://github.com/Open-Reaction-Database/ord-schema/blob/master/examples/2_Nielsen_Deoxyfluorination_Screen/example_nielsen.ipynb) and the [Ahneman example](https://github.com/Open-Reaction-Database/ord-schema/blob/master/examples/9_Ahneman_Science_CN_Coupling/example_Ahenman.ipynb), I'm considering this closed
