### ISSUE TITLE
Stock solutions from vendors

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#444]
From Kjell Jorner: Regarding stock solutions, they may be bought from manufacturers and original recipe unknown

(re: not allowing solutions to be defined by concentration in the schema)

**Comment by kjelljorner** [comment]
Now it's been a long time since I was in the lab, but typically you would use standard-made reagents with specific concentrations. Especially if they are difficult or dangerous to make. On example: https://www.sigmaaldrich.com/catalog/product/aldrich/197343

**Comment by skearnes** [comment]
This suggests that #372 should be higher priority
