### ISSUE TITLE
Why does Ketcher return a Molfile?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#454]
Any reason not to just have it return SMILES?

**Comment by connorcoley** [comment]
I made this decision very consciously:
(1) The MolFile is a more direct representation of what the user drew in Ketcher, and can contain information that SMILES cannot, theoretically
(2) It is jarring to draw a molecule with Ketcher, close the window, and have it be in a completely new orientation when you open Ketcher back up. Preserving the MolFile lets us reopen the window with the molecule drawn in the same manner

**Comment by skearnes** [comment]
SGTM, thanks.
