### ISSUE TITLE
Amount message?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#506]
As I was reviewing https://github.com/Open-Reaction-Database/ord-editor/issues/3, I found myself wondering why we don't have an `Amount` message:

```proto
message Amount {
  oneof kind {
    Mass mass = 1;
    Moles moles = 2;
    Volume volume = 3;
  }
}
```

This would change accessors like `getattr(compound, compound.WhichOneof('amount')).value` to `getattr(compound.amount, compound.amount.WhichOneof('kind')).value` but might be more readable since "Amount" will always show up in the pbtxt.

This would slightly reduce code duplication with the other amount oneof fields (in `CrudeComponent` and `Workup`) but also require additional validation to e.g. make sure that `moles` is not used when it is not appropriate.

I don't feel strongly about this either way, but wanted to bring it up as an opportunity to be slightly more explicit/consistent as we are making changes to the schema.

@connorcoley WDYT?

**Comment by skearnes** [comment]
Gentle ping...

**Comment by connorcoley** [comment]
I was considering that as well...we do reuse Amounts in a few different places. I don't love the additional level of nesting in the programmatic definitions but overall I think it makes sense from a code reusability perspective. I can't think of any significant downsides, can you?

**Comment by skearnes** [comment]
No, I don't see any significant downsides. I think an `Amount` message would be consistent with the way we've factored out other groups of things.

I'll create a PR to your PR for review.
