### ISSUE TITLE
Code file reaction_pb2.py Not Found.

### ISSUE THREAD

**Issue by LeoAokma** [open-reaction-database/ord-schema#535]
**Describe the bug**
In ord_schema.proto folder, could not find the code file reaction_pb2.py

**Expected behavior**
Expect to have this file and make the code running.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1.0
 - Browser safari

**Comment by skearnes** [comment]
Hi there, the python wrappers are generated by protoc when you run `python setup.py install`.
