### ISSUE TITLE
Using *.pb as the source of truth

### ISSUE THREAD

**Issue by skearnes** [open-reaction-database/ord-schema#545]
Our current workflows assume that plain-text *.pbtxt files are the source of truth. This has pros and cons:

Pros:
* Human-readable

Cons:
* Large files (although git compresses them, they can't easily be navigated on GitHub)
* Very slow to parse into protocol buffers

**Proposal:** move to using *.pb (binary proto wire format) as the source of truth. This also has pros and cons:

Pros:
* Very fast I/O
* Small file size

Cons:
* Not human-readable; cannot be directly inspected

To compensate for the cons, we could do the following:
* Attach plain text *.pbtxt (or even JSON) records generated from the *.pb files to each release/tag (see [release assets](https://docs.github.com/en/github/administering-a-repository/about-releases#storage-and-bandwidth-quotas))
* Include CI checks that validate the *.pb files, just like we do now with the *.pbtxt files

Note that I'm explicitly *not suggesting* that we require ord-data submissions to be in *.pbtxt form, either; some of the submissions are going to be too large for GitHub to reasonably handle as plain text.

WDYT?

**Comment by skearnes** [comment]
Any comments on this? Tacit approval?

**Comment by michaelmaser** [comment]
> **Proposal**: move to using *.pb (binary proto wire format) as the source of truth.

SGTM

**Comment by antonkast-google** [comment]
Why do I/O latencies matter? We can't browse either way. Is the idea to optimize indexing latency? Who cares about that?

-1 for copying .pb to .pbtxt. It's a form of caching and would invite confusion.

Unless I'm missing something, I favor the readable form.

**Comment by skearnes** [comment]
> Why do I/O latencies matter? We can't browse either way. Is the idea to optimize indexing latency? Who cares about that?

Our submission and validation pipelines would run much faster if we used .pb.
> 
> -1 for copying .pb to .pbtxt. It's a form of caching and would invite confusion.

Many people would like something that they don't need to use a proto compiler to read. The JSON export would provide this. Since neither the .pbtxt nor the .json would be part of the official repo (just attached to releases), I don't see much risk of confusion while providing multiple formats for people to inspect and use.
> 
> Unless I'm missing something, I favor the readable form.

I don't think the current form is actually very readable. Inspecting a single file is a pain and will only get worse if we continue to get large HTE submissions. We're planning a submission that will contain millions of reactions at the moment, which just doesn't make sense for plain text encoding. Additionally, we have had requests to support large lists of compound identifiers (e.g. specific 3D conformations of catalysts) that also break the usability of plain text.

I think the question is less about "if it's not a clear yes it's a clear no" and more about "we should have used .pb in the first place, is there any reason not to switch?"

**Comment by connorcoley** [comment]
Reliance on pbtxt files won't scale well as the database grows and as datasets get larger. With the USPTO data, we're already looking at multiple GB of data when stored as pbtxt, right? Using GitHub, we'll need to fragment this into a set of ≤100 MB files. Inspecting individual reactions (or _small_ datasets) as pbtxt is convenient, but the need to store datasets as pbtxt might not scale. This is more important to me than I/O

I think the con of using *.pb (lack of readability) can be overcome through simple command-line scripts to make it straightforward to convert from *.pb to *.pbtxt. Conversion would be easy through the current editor if one can, e.g., upload a *.pb and choose which format to use when downloading.

**Comment by michaelmaser** [comment]
For context, with the Santanilla dataset ("7d", 1536 reactions):

.pbtxt:
`wget` download time: 3.686128614000154s
`message_helpers.load_message` load time: 13.422402256999703s

.pb:
`wget` download time: 1.615136507999523s
`message_helpers.load_message` load time: 0.1841710940007033s

**Comment by skearnes** [comment]
We decided to move forward with this; see #548
