### ISSUE TITLE
Clarify use of workup.amount field

### ISSUE THREAD

**Issue by michaelmaser** [open-reaction-database/ord-schema#573]
There was some confusion in open-reaction-database/ord-data#57 about the use of the `workup.amount` field. Some workup types such as `ADDITION` and `FILTRATION` can have `workup.input` species that have `workup.input.component.amount` fields. The confusion was over which amount field should be defined, and as a result both were included at first, where each `component.amount` was defined and the high level `workup.amount` was the total summed volume. The `workup.amount` field was added to the proto to handle `ALIQUOT` amounts specifically, and if given we treat the specified value as the current material amount that's carried through later steps. This would be an undesired outcome if the high level amount did not refer to an aliquot, such as in this example. There is a comment in `reaction.proto` to explain this, but the submission was done on the editor. The question now is: should `workup.amount` be renamed to, e.g., `workup.aliquot_amount` to avoid ambiguity on the user end? Or, should that field only be available on the editor if the workup type `ALIQUOT` is used (it would still be available in programmatic submissions)? Or, something else? Thoughts? Related to #503.

**Comment by connorcoley** [comment]
I would suggest two changes:

1. Rename that entry on the web form. I don't think we need to change the field name in the proto
2. Add in more extensive workup validations. For example, `amount` should only be used when the type of ALIQUOT -- this kind of logic is easy to add to validations.py and these errors will be clearly visible on the web editor too
