### ISSUE TITLE
Missing dependency in example_requirements.txt

### ISSUE THREAD

**Issue by DocMinus** [open-reaction-database/ord-schema#594]
Not a bug, not a deal-breaker, but just to note that the following notebook makes use of _tqdm_ which currently is missing from the example_requirements.txt:
[examples/submissions/1_Santanilla_Nanomole_HTE/](https://github.com/open-reaction-database/ord-schema/blob/main/examples/submissions/1_Santanilla_Nanomole_HTE/example_Santanilla.ipynb)
Alternatively, the notebook could contain `!pip install ...` ?

**Comment by skearnes** [comment]
Thanks; I'll fix this!

**Comment by skearnes** [comment]
Fixed in https://github.com/open-reaction-database/ord-schema/pull/619 (back in January)
