### ISSUE TITLE
Setup.py is missing install_requires

### ISSUE THREAD

**Issue by marcosfelt** [open-reaction-database/ord-schema#600]
setup.py is missing `install_requires`, so dependencies are not installed when installing from pypi.  Happy to submit a PR for this if it is indeed a bug.

**Comment by marcosfelt** [comment]
Relevant to this is that rdkit is now [installable via pypi](https://pypi.org/project/rdkit-pypi/) on Mac and Linux.

**Comment by connorcoley** [comment]
I don't think the pypi installation of RDKit is officially supported yet; i.e., this one works, but it's not guaranteed that it will be actively maintained and updated
