### ISSUE TITLE
In auto-generated DOI list, show dataset description

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-schema#606]
This will clarify where contributions came from in terms of _specific_ figures/tables as subsets of papers, which should help us detect duplicate submissions.

**Comment by skearnes** [comment]
Would probably also be good to include the number of reactions for each dataset; we can make this into a table instead of just a list.

**Comment by skearnes** [comment]
Would probably also be good to include the number of reactions for each dataset; we can make this into a table instead of just a list.

**Comment by skearnes** [comment]
@connorcoley PTAL at https://github.com/open-reaction-database/ord-data/blob/431b60eb3c81b5162f567e2be87dc00fa2451e74/README.md

**Comment by connorcoley** [comment]
The new table looks great (except the USPTO attribution is to "we, D."). This is making me realize we should be enforcing more meaningful descriptions of datasets. Should this table also include the dataset's name?

**Comment by skearnes** [comment]
PTAL; added names where available (and used 'link' when not). Also fixed the Lowe dataset citation. The downside is that the table overflows a bit now and it's hard to see the descriptions...

**Comment by connorcoley** [comment]
I think the additional information is nice even if it makes the table wider. I will reiterate that we should start enforcing that names/descriptions be informative

**Comment by skearnes** [comment]
Swapped "description" and "reactions" columns to make it a bit easier to read.

**Comment by skearnes** [comment]
Superseded by https://github.com/open-reaction-database/ord-interface/pull/39
