### ISSUE TITLE
A `phase` or `texture` field for Compound and ReactionInput

### ISSUE THREAD

**Issue by qai222** [open-reaction-database/ord-schema#696]
**Is your feature request related to a problem? Please describe.**
The physical state of reactants can be important for reproducing a reaction (especially the choice of appropriate addition devices). So far no dedicated fields for this.

**Describe the solution you'd like**
A `phase` or `texture` field at both `Compound` and `ReactionInput` levels. The value can be a `Texture` message, although it does not include the gas phase explicitly.

**Comment by bdeadman** [comment]
I will check this and update status. Might need to open an issue on ord-interface to provide new fields there.

**Comment by bdeadman** [comment]
Need to add a texture input field to ReactionInput on the contributions interface.

**Comment by skearnes** [comment]
@bdeadman is this issue done?

**Comment by bdeadman** [comment]
ord-schema side was done in [ord-schema PR 698](https://github.com/open-reaction-database/ord-schema/pull/698). Just need to update the interfaces. There is an issue for that open-reaction-database/ord-interface#75 so will close this one.
