### ISSUE TITLE
google.protobuf.message.DecodeError: Wrong wire type in tag.

### ISSUE THREAD

**Issue by Da-vid21** [open-reaction-database/ord-schema#704]
**Describe the bug**
I was trying to parse the ord-data provided and I keep on getting this error when trying to use `ParseFromString` function

**To Reproduce**
1. Create a new py file
2. Use this code
  `import gzip`
  `from ord_schema.proto import reaction_pb2`
  `reaction = reaction_pb2.Reaction()`
  `with gzip.open('data/00/ord_search_results.pb.gz', 'rb') as f:`
  `    data = f.read()`
  `    reaction.ParseFromString(data)`
  `print(reaction)`
3. See error

**Expected behavior**
I want to be able to read the dataset so that I can parse the SMILES and chemical reaction name 

**Screenshots**
<img width="1093" alt="image" src="https://github.com/open-reaction-database/ord-schema/assets/82111747/7d5720e8-a1c6-4e28-8a37-21779393c32e">

**Desktop (please complete the following information):**
 - OS: MacOs
 - PyCharm
 - Python 3.8
 - ord-schema 0.3.25

**Comment by skearnes** [comment]
Hi @Da-vid21, the search results should give you a `Dataset`, which won't load into a `Reaction`. Could you send me the search results you downloaded and I can send you a snippet to read them?

**Comment by bdeadman** [comment]
Closed due to inactivity.
