### ISSUE TITLE
Add Pipette as AdditionDevice option

### ISSUE THREAD

**Issue by connorcoley** [open-reaction-database/ord-schema#708]

**Comment by bdeadman** [comment]
Issue #607  can also be addressed at the same time.

**Comment by bdeadman** [comment]
Pull request #718 will add pipette, and positive displacement pipette as options.

**Comment by skearnes** [comment]
@bdeadman is this issue done? Now it's just interface-side updates that remain?

**Comment by bdeadman** [comment]
@skearnes 
yes the schema side is done. Just waiting for the interface which has its own issue, so we can close this one.
