### ISSUE TITLE
`add_rdkit` not found in `ord_schema.orm.database`

### ISSUE THREAD

**Issue by qai222** [open-reaction-database/ord-schema#721]
**Describe the bug**
In [orm readme](https://github.com/open-reaction-database/ord-schema/blob/bbe1ff5ee6f48851571444ab18ceb2e4144e30d2/ord_schema/orm/README.md?plain=1#L147) the rdkit tables is updated using a function called `add_rdkit`
```python
# from ord_schema.orm.database import add_dataset, add_rdkit
    with Session(engine) as session:
        add_dataset(dataset, session)
        session.flush()
        add_rdkit(session)
        session.commit()
```
This function can no longer be found in `ord_schema.orm.database`. Instead I'm using
```python
    with Session(engine) as session:
        add_dataset(dataset, session)
        session.flush()
        if update_rdkit:
            update_rdkit_tables(dataset_id, session)
            update_rdkit_ids(dataset_id, session)
        session.commit()
```
I'm not sure this is the right way though.

**Comment by skearnes** [comment]
The readme is out of date; the current usage is actually tested here: https://github.com/open-reaction-database/ord-schema/blob/main/ord_schema/orm/conftest.py#L30

**Comment by qai222** [comment]
> The readme is out of date; the current usage is actually tested here: https://github.com/open-reaction-database/ord-schema/blob/main/ord_schema/orm/conftest.py#L30

Thanks! Just curious, what would happen if the second `session.flush()` is not called?
```python
                if rdkit_cartridge:
                    session.flush()
                    update_rdkit_tables(dataset.dataset_id, session)
                    session.flush()
                    update_rdkit_ids(dataset.dataset_id, session)
```

**Comment by skearnes** [comment]
> > The readme is out of date; the current usage is actually tested here: https://github.com/open-reaction-database/ord-schema/blob/main/ord_schema/orm/conftest.py#L30
> 
> Thanks! Just curious, what would happen if the second `session.flush()` is not called?
> 
> ```python
>                 if rdkit_cartridge:
>                     session.flush()
>                     update_rdkit_tables(dataset.dataset_id, session)
>                     session.flush()
>                     update_rdkit_ids(dataset.dataset_id, session)
> ```

`update_rdkit_ids` matches IDs in the `ord.reaction` and `rdkit.reactions` tables; the flush is required to make sure that the `rdkit.reactions` IDs are available for matching.
