### ISSUE TITLE
' type: NAME': Enum type "ord.ReactionIdentifier.ReactionIdentifierType" has no value named NAME.

### ISSUE THREAD

**Issue by bdeadman** [open-reaction-database/ord-schema#727]
I've seen this in two datasets generated by users in Python. They both tried to add a NAME field as a reaction identifier. ORD does not currently have a NAME enum option at the reaction identifier level. Often the more appropriate labels are REACTION_TYPE for a description of the reaction category, or CUSTOM for user specific identifiers like ELN numbers.

When uploading such pbtxt files to the interface you will receive an error:

Error: 3:11 : ' type: NAME': Enum type "ord.ReactionIdentifier.ReactionIdentifierType" has no value named NAME.

To discuss - is there a need for a NAME field in reaction identifiers? We would still need to ensure more appropriate labels are used where possible.

**Comment by bdeadman** [comment]
OK, it seems at least one of these users are still on version 0.3.37 of ord-schema which did have the NAME option, but this has since changed to REACTION_TYPE.

**Comment by skearnes** [comment]
Yes we made this decision deliberately to remove NAME in favor of REACTION_TYPE; see https://github.com/open-reaction-database/ord-schema/pull/666. IIRC we wanted to be more explicit about the meaning of that field? @connorcoley?
