### ISSUE TITLE
Use CompoundIdentifier instead of Compound for solvent and support?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#9]
Would it make sense to use `CompoundIdentifier` instead of `Compound` for the `solvent` and `support` fields of `Amount`? This would be a simpler API (one less level of nesting); additionally, it makes things more sane over all, since currently you could recurse into `Compound` indefinitely.

The question is whether we expect these fields to specify more information than just the identifier? If so, do we need to extend `Amount` to include things like mixture percentages? Or on the other end, could we remove the `repeated` qualifier from these fields if we only expect there to be a maximum of one solvent or support?

**Comment by connorcoley** [comment]
We definitely need to be able to record unequal co-solvent mixtures; for that reason, I thought it necessary that each ```solvent``` be able to have its own amount to define the ratio. In most cases, a solution will be in a single solvent, but it's not that rare to have solvent mixtures.

I'll need to think more about the support, but I imagine it's a similar situation.

**Comment by skearnes** [comment]
Sounds good, thanks.
